version: "3.4"

x-var: &USERNAME
   corona-app
x-var: &USERPWD
    corona-app
x-var: &DATABASE
    corona-app

services: 
    mysqldb:
        container_name: mysqldb
        image: mysql:5.7
        ports:
            - 3306:3306
        expose:
            - 3306
        environment: 
            MYSQL_DATABASE: *DATABASE
            MYSQL_USER: *USERNAME
            MYSQL_PASSWORD: *USERPWD
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - corona-api-db:/var/lib/mysql
        networks:
            - db-net
        # user: 
        #     1000:1000
    corona-api:
        container_name: corona-api
        build:
            context: springboot-api
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        expose:
            - 8080
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/corona-app
            SPRING_DATASOURCE_USERNAME: *USERNAME
            SPRING_DATASOURCE_PASSWORD: *USERPWD
            SPRING_JPA_HIBERNATE_DDL-AUTO: update
        networks:
            - db-net
            - infra-net
        depends_on: 
            - mysqldb
    corona-client-app:
        container_name: corona-client-app
        build:
            context: clientApp
            dockerfile: Dockerfile
        ports:
            - 3000:80
        depends_on: 
            - corona-api
        networks: 
            - infra-net
        stdin_open: true


volumes:
    corona-api-db:
networks: 
    db-net:
    infra-net:

